# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui_files\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(790, 455)
        loginWindow.setMinimumSize(QtCore.QSize(790, 455))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        loginWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 810, 450))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 371, 411))
        self.label.setStyleSheet("border-image: url(:/icons-logo/icons-logo/Two friends.png);\n"
"border-bottom-left-radius: 30px;\n"
"border-top-left-radius: 30px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 370, 410))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-bottom-left-radius: 30px;\n"
"border-top-left-radius: 30px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(380, 10, 400, 410))
        self.label_3.setStyleSheet("background-color : rgba(255,255,245,255);\n"
"border-bottom-right-radius: 30px;\n"
"border-top-right-radius: 30px;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.logoLabel = QtWidgets.QLabel(self.widget)
        self.logoLabel.setGeometry(QtCore.QRect(485, 30, 190, 120))
        self.logoLabel.setStyleSheet("image: url(:/icons-logo/icons-logo/Logo_tweet.png);")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.useridlineEdit = QtWidgets.QLineEdit(self.widget)
        self.useridlineEdit.setGeometry(QtCore.QRect(485, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.useridlineEdit.setFont(font)
        self.useridlineEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.useridlineEdit.setObjectName("useridlineEdit")
        self.passwordlineEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordlineEdit.setGeometry(QtCore.QRect(485, 235, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.passwordlineEdit.setFont(font)
        self.passwordlineEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.passwordlineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passwordlineEdit.setObjectName("passwordlineEdit")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(740, 20, 30, 30))
        self.exitButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color : rgba(255,255,245, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(222,193,158, 50);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons-logo/icons-logo/icons8-x-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(25, 25))
        self.exitButton.setObjectName("exitButton")
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setGeometry(QtCore.QRect(485, 295, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(170,137,84,255);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgba(187,161,118,255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: rgba(187,161,118,255);\n"
"    border-radius: 10px;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setGeometry(QtCore.QRect(485, 340, 135, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"}\n"
"")
        self.label_1.setTextFormat(QtCore.Qt.RichText)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.signupLabel = QtWidgets.QLabel(self.widget)
        self.signupLabel.setGeometry(QtCore.QRect(621, 340, 55, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signupLabel.setFont(font)
        self.signupLabel.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #649ca4; /* Text color on hover */\n"
"    text-decoration: underline; /* Underline on hover */\n"
"}")
        self.signupLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.signupLabel.setObjectName("signupLabel")
        loginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "MainWindow"))
        self.useridlineEdit.setPlaceholderText(_translate("loginWindow", "User ID"))
        self.passwordlineEdit.setPlaceholderText(_translate("loginWindow", "Password"))
        self.exitButton.setToolTip(_translate("loginWindow", "<html><head/><body><p>Exit</p></body></html>"))
        self.loginButton.setText(_translate("loginWindow", "Log In"))
        self.label_1.setText(_translate("loginWindow", "<html><head/><body><p>Don\'t have an account?</p></body></html>"))
        self.signupLabel.setToolTip(_translate("loginWindow", "Sign up for an account."))
        self.signupLabel.setText(_translate("loginWindow", "<html><head/><body><u>Sign Up!</u></body></html>"))
import res_rc
