# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui_files\Signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signupWindow(object):
    def setupUi(self, signupWindow):
        signupWindow.setObjectName("signupWindow")
        signupWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        signupWindow.resize(380, 635)
        signupWindow.setMinimumSize(QtCore.QSize(380, 635))
        signupWindow.setToolTip("")
        signupWindow.setToolTipDuration(-1)
        self.centralwidget = QtWidgets.QWidget(signupWindow)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 360, 600))
        self.label.setStyleSheet("background-color: rgba(255,255,245,255);\n"
"border-radius: 30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 340, 230))
        self.label_2.setStyleSheet("border-top-right-radius: 30px;\n"
"border-top-left-radius: 30px;\n"
"border-image: url(:/icons-logo/icons-logo/Girl on phone.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(40, 290, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 340, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 440, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 390, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 490, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom: 7px;\n"
"padding-left: 15px")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(320, 560, 30, 30))
        self.returnButton.setToolTipDuration(-1)
        self.returnButton.setStatusTip("")
        self.returnButton.setWhatsThis("")
        self.returnButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color : rgba(255,255,245, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(222,193,158, 50);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.returnButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons-logo/icons-logo/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.returnButton.setIcon(icon)
        self.returnButton.setIconSize(QtCore.QSize(25, 25))
        self.returnButton.setObjectName("returnButton")
        self.signupButton = QtWidgets.QPushButton(self.centralwidget)
        self.signupButton.setGeometry(QtCore.QRect(40, 550, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.signupButton.setFont(font)
        self.signupButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(170,137,84,255);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgba(187,161,118,255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: rgba(187,161,118,255);\n"
"    border-radius: 10px;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.signupButton.setObjectName("signupButton")
        self.label.raise_()
        self.lineEdit_1.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_5.raise_()
        self.returnButton.raise_()
        self.signupButton.raise_()
        self.label_2.raise_()
        signupWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signupWindow)
        self.statusbar.setObjectName("statusbar")
        signupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(signupWindow)
        QtCore.QMetaObject.connectSlotsByName(signupWindow)

    def retranslateUi(self, signupWindow):
        _translate = QtCore.QCoreApplication.translate
        signupWindow.setWindowTitle(_translate("signupWindow", "MainWindow"))
        self.lineEdit_1.setPlaceholderText(_translate("signupWindow", "Email"))
        self.lineEdit_2.setPlaceholderText(_translate("signupWindow", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("signupWindow", "City"))
        self.lineEdit_3.setPlaceholderText(_translate("signupWindow", "Username"))
        self.lineEdit_5.setPlaceholderText(_translate("signupWindow", "Timezone"))
        self.returnButton.setToolTip(_translate("signupWindow", "<html><head/><body><p>Return</p></body></html>"))
        self.signupButton.setText(_translate("signupWindow", "Sign Up"))
import res_rc
