# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui_files\Warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_warningWindow(object):
    def setupUi(self, warningWindow):
        warningWindow.setObjectName("warningWindow")
        warningWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        warningWindow.resize(340, 170)
        warningWindow.setMinimumSize(QtCore.QSize(340, 170))
        self.buttonBox = QtWidgets.QDialogButtonBox(warningWindow)
        self.buttonBox.setGeometry(QtCore.QRect(130, 110, 80, 30))
        self.buttonBox.setStyleSheet("QDialogButtonBox QPushButton{\n"
"background-color: rgba(170,137,84,255);\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:hover {\n"
"background-color: rgba(187,161,118,255);\n"
"\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:pressed {\n"
"background-color: rgba(187,161,118,255);\n"
"padding-left: 1px;\n"
"padding-top: 1px;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(warningWindow)
        self.label.setGeometry(QtCore.QRect(10, 5, 320, 160))
        self.label.setStyleSheet("border: 2px solid rgba(46,82,101,120);\n"
"background-color: rgba(255,255,245,255);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.warningText = QtWidgets.QLabel(warningWindow)
        self.warningText.setGeometry(QtCore.QRect(25, 30, 291, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.warningText.setFont(font)
        self.warningText.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"}\n"
"")
        self.warningText.setText("")
        self.warningText.setScaledContents(False)
        self.warningText.setAlignment(QtCore.Qt.AlignCenter)
        self.warningText.setObjectName("warningText")
        self.label.raise_()
        self.warningText.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(warningWindow)
        self.buttonBox.accepted.connect(warningWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(warningWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(warningWindow)

    def retranslateUi(self, warningWindow):
        _translate = QtCore.QCoreApplication.translate
        warningWindow.setWindowTitle(_translate("warningWindow", "Dialog"))
import res_rc
